// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFAUd1k0zyfE3ZkCuwm7NCZuJF_UaCfM',
    appId: '1:483912834158:web:25e5c48573e83efc2f5a7f',
    messagingSenderId: '483912834158',
    projectId: 'flutter-project-47c1d',
    authDomain: 'flutter-project-47c1d.firebaseapp.com',
    storageBucket: 'flutter-project-47c1d.firebasestorage.app',
    measurementId: 'G-QBC9NWJBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWOkPslKkATtmarEfSJImjXSb_WqAP1k',
    appId: '1:483912834158:android:6d120e3b4b52d8b02f5a7f',
    messagingSenderId: '483912834158',
    projectId: 'flutter-project-47c1d',
    storageBucket: 'flutter-project-47c1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-_P7y_0qo-wgxqTuUlvYAyLKfXnb2wg',
    appId: '1:483912834158:ios:c0ae9e72a36b9cb22f5a7f',
    messagingSenderId: '483912834158',
    projectId: 'flutter-project-47c1d',
    storageBucket: 'flutter-project-47c1d.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-_P7y_0qo-wgxqTuUlvYAyLKfXnb2wg',
    appId: '1:483912834158:ios:c0ae9e72a36b9cb22f5a7f',
    messagingSenderId: '483912834158',
    projectId: 'flutter-project-47c1d',
    storageBucket: 'flutter-project-47c1d.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCFAUd1k0zyfE3ZkCuwm7NCZuJF_UaCfM',
    appId: '1:483912834158:web:ccc7b99bb9e6d05b2f5a7f',
    messagingSenderId: '483912834158',
    projectId: 'flutter-project-47c1d',
    authDomain: 'flutter-project-47c1d.firebaseapp.com',
    storageBucket: 'flutter-project-47c1d.firebasestorage.app',
    measurementId: 'G-9JK423DJRJ',
  );

}